### model
model_name_or_path: meta-llama/Meta-Llama-3-8B
quantization_bit: 4

### method
stage: sft
do_train: true
finetuning_type: full
use_qbadam: true
badam_mode: layer
badam_switch_mode: ascending
badam_switch_interval: 50
badam_verbose: 1

### dataset
dataset: alpaca_gpt4_en
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
# preprocessing_num_workers: 64
preprocessing_num_workers: 16


### output
output_dir: /home/ubuntu/date/test-ckpts/qbadam_v2_llama3_K50
logging_steps: 10
save_steps: 700
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 0.1
pure_bf16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500
